### ISSUE TITLE
Design Link & Upload Russian Whitepaper to the website

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#103]
https://backend.keep.network/whitepaper-ru

**Comment by Shadowfiend** [comment]
Are we trying to update a different version here?

**Comment by elizapetrovska** [comment]
Could you explain your question a bit please :)

**Comment by Gluzman** [comment]
FYI—two parts to this:

1. Design it into the next web version
2. Erin will most likely upload so she should be tagged as a heads up.

**Comment by liz-shinn** [comment]
This issue resolved by removal of whitepaper referenced here: https://github.com/keep-network/website/issues/169
