### ISSUE TITLE
Gather content for a no-date development progress roadmap

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#104]
A straight-line visual roadmap with things we tackled but no dates

https://docs.google.com/document/d/11gXUBvJjt6U2VgYDQvormAHBaivTlxzweSN-bzxno9w/edit

**Comment by Gluzman** [comment]
@elizapetrovska can you provide some context on what this means?

**Comment by pdyraga** [comment]
Hey, can please we detach this item from Sprint 4 so that I can close that sprint? (I can't do it myself)

Should it be moved to Sprint 5?
