### ISSUE TITLE
Upload Updated Business Primer

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#106]
see the picture attached

**Comment by elizapetrovska** [comment]
<img width="633" alt="Screenshot 2019-03-22 at 10 32 58 AM" src="https://user-images.githubusercontent.com/35865315/54834353-fe2d6b80-4c8d-11e9-987f-759102c8fba5.png">

**Comment by liz-shinn** [comment]
Issue resolved by removal of whitepaper and business primer from website: https://github.com/keep-network/website/issues/169
