### ISSUE TITLE
Update people in the Primer

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#111]
Text and photo below

**Comment by elizapetrovska** [comment]
Dmitry Paremski, Developer

Dmitry holds well-honed skills in computer science. He has a broad experience of full-stack software engineering and has crafted software for small startups as well as big international corporations.

**Comment by elizapetrovska** [comment]
![dmitry](https://user-images.githubusercontent.com/35865315/55093861-43351180-5083-11e9-8b59-6aadf5633e3c.jpg)

**Comment by Gluzman** [comment]
and then re-upload?

**Comment by elizapetrovska** [comment]
Yes, but I would love to announce the new Primer this week, so for now can be without Dmitry

**Comment by Gluzman** [comment]
would it make more sense to have a more dynamic form of the primer altogether, @Shadowfiend ? like say i dunno, a webpage?

**Comment by drknudy** [comment]
I think a webpage would be awesome with the option to download a PDF. Less friction for the user that way as well.

**Comment by Gluzman** [comment]
something to consider... well let's hold on this update and make the update in a batch with any other updates. this is per my convo with @LWallendal

**Comment by Shadowfiend** [comment]
Yep, webpage :thumbsup:, batch :thumbsup:, PDF download :thumbsup: (though that'll be the more annoying bit if we have a web version, particularly in terms of keeping it synchronized content-wise).

**Comment by elizapetrovska** [comment]
But it is PDF downloadable now, isn't it?

**Comment by Shadowfiend** [comment]
Correct. The question is whether we want a web version as well, and if we do how we keep the content synchronized.

**Comment by Gluzman** [comment]
We have similar issues with the PDF and web currently: not accessible by all. I do not have a template created for the PDF version that someone without Indesign experience could use, nor do we have a CMS for any of our websites where anyone could come in and update/publish new media.

**Comment by Shadowfiend** [comment]
We don't need a CMS, just something that's a little more accessible than InDesign. Right now one person can update this---if we make it two people instead of one we've already doubled our bandwidth :) For example, if we pulled most of the content in pieces from this repository, @elizapetrovska is already updating [Slack welcome messages and moderator lists](https://github.com/keep-network/website/tree/master/slack), and anyone with write access here can do the same with a little bit of up-front learning and some elbow grease.

**Comment by elizapetrovska** [comment]
- Dmitry Paremski, Developer

Dmitry holds well-honed skills in computer science. He has a broad experience of full-stack software engineering and has crafted software for small startups as well as big international corporations.


- Nicholas Evans, Developer

Nicholas has taken some miscellaneous contracts in the space, but most recently worked at ConsenSys, where he held sessions on smart contract development and security, solved many technical challenges, and trained developers on Solidity.


- Olivia Lovenmark

Olivia is an accomplished technical writer and content marketer, joining Keep from the marketing team at BitGo. She has helped companies message themselves to the world since 2010.


- Jarrell James 

Jarrell is an emerging technology strategist whose career has been spent bringing next-generation tools to consumer and enterprise markets all over the world. He has an extensive history in many web 3.0 systems.

**Comment by elizapetrovska** [comment]
Remove Raghav and Marcin

**Comment by elizapetrovska** [comment]
- Liam Zebedee

Liam is passionate about emerging tech, fluent in rapid prototyping and experimentation. Programming since 11, he is strongly rooted in the human-centredness of technology and design.

![liam](https://user-images.githubusercontent.com/35865315/59620116-ad44dc00-90f1-11e9-8def-97108cdd3628.jpg)

**Comment by elizapetrovska** [comment]
UPD: this is done, coordinated with Liz via email

**Comment by elizapetrovska** [comment]
Sloan Thompson, Head of DevOps

"Sloan is passionate about bridging operations and engineering practices, providing robust infrastructure, systems, and meaningful engineering experience.  Prior to Keep Sloan worked in the supply chain, helping to bring aging systems and processes into today's IT landscape."

**Comment by elizapetrovska** [comment]
in process with Liz

**Comment by liz-shinn** [comment]
Primer is up-to-date with the above info! Do we want to keep this issue open for future Primer updates, or go ahead and close it?

**Comment by elizapetrovska** [comment]
Not sure if we want to continue the side conversation, but the updates are definitely done :)

**Comment by liz-shinn** [comment]
Cool! Going to go ahead and close this issue then.
