### ISSUE TITLE
Update Keep team portraits on website

### ISSUE THREAD

**Issue by Gluzman** [keep-network/website#113]

**Comment by liz-shinn** [comment]
Another round of updates needed here for the team images taken at the onsite in 2020.

**Comment by Gluzman** [comment]
fyi those portraits didn't turn out as great as had hoped, so let's remain open with the source of portraits - can you make a punch list of folks who need removal/addition?

**Comment by liz-shinn** [comment]
Oh good to know. Here are the folks that should be included in the Keep team:

[ ] matt
[ ] corbin
[ ] antonio
[ ] carolyn
[ ] michael
[ ] liz 
[ ] piotr
[ ] promethea
[ ] sloan
[ ] nik
[ ] rafal
[ ] kuba
[ ] nicholas
[ ] dmitry
[ ] liam
[ ] lukasz
[ ] erin
[ ] laura

**Comment by liz-shinn** [comment]
Working on this now – have the headshots and social info good to go. Blocked by bug in CMS. Will circle back!

Headshots here: https://www.figma.com/file/11SS32lywNco0eVQMyhDBI/Team-Headshots?node-id=0%3A1

Social info & team members that need to be added here:

Liz Shinn
https://github.com/liz-shinn
https://www.linkedin.com/in/lizshinndesign
https://twitter.com/lizshinndesign
https://keybase.io/lizshinn

Rafal Czajkowski
https://github.com/r-czajkowski
http://keybase.io/rczajkowski

Łukasz Zimnoch
https://github.com/lukasz-zimnoch
http://keybase.io/lukaszzimnoch

**Comment by liz-shinn** [comment]
Updated [on the website](keep.network)! Closing this one out.
