### ISSUE TITLE
Adjust hover + click highlight placement

### ISSUE THREAD

**Issue by Gluzman** [keep-network/website#114]

**Comment by Gluzman** [comment]
<img width="721" alt="Screen Shot 2019-04-05 at 10 44 01" src="https://user-images.githubusercontent.com/7621557/55636389-c4ca2500-5790-11e9-8410-86caa44074fd.png">

should be flush against divider line.

**Comment by liz-shinn** [comment]
Current implementation:
<img width="1440" alt="Fullscreen_11_18_19__4_24_PM" src="https://user-images.githubusercontent.com/57226633/69095278-f93cd980-0a1f-11ea-8dc2-dbb7e28c0f6e.png">

Looks like this has been fixed! Going to close this issue.
