### ISSUE TITLE
Update Slack logo

### ISSUE THREAD

**Issue by Gluzman** [keep-network/website#118]

**Comment by liz-shinn** [comment]
Currently:
<img width="181" alt="Keep_Network" src="https://user-images.githubusercontent.com/57226633/69091800-0904ef80-0a19-11ea-9584-7d7d5c0580da.png">

Should be updated to new Slack logo:
<img width="497" alt="Keep_Website" src="https://user-images.githubusercontent.com/57226633/69092062-9c3e2500-0a19-11ea-9fd0-2f5e8a8bc044.png">

**Comment by liz-shinn** [comment]
New Slack logo is in Figma file [here](https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=556%3A0):

**Comment by liz-shinn** [comment]
This issue fixed by implementation of Discord logo.
