### ISSUE TITLE
No Dates Roadmap of Keep 

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#121]
A straight-line visual overall Keep roadmap with things we tackled but no dates. The draft is here https://docs.google.com/document/d/11gXUBvJjt6U2VgYDQvormAHBaivTlxzweSN-bzxno9w/edit

 @Shadowfiend would love your eyes on this and get some more info

**Comment by Shadowfiend** [comment]
Let's include a problem statement in here (we've [discussed a touch](https://www.flowdock.com/app/cardforcoin/growth/threads/-c6A5zc6fpapN6n5MZAT5KI8zKp)). By problem statement I mean a general outline of what we're trying to solve, who we're solving it for, and why we think it's important.

That will give context to the work, and should help us start having the right discussions to figure out how to present the roadmap.

**Comment by elizapetrovska** [comment]
I think the problem to solve is to show legitimacy and transparency. 
While code is private and the sale is "soon", and if we want conversations to be focused around tech, let's give them tech to talk about. Besides, people keep asking for it.

**Comment by elizapetrovska** [comment]
https://www.flowdock.com/app/cardforcoin/keep/threads/3VyTCk-BtS-9uE0nmOnafrHTXjM

a thread about Beacon roadmap in the near future

**Comment by elizapetrovska** [comment]
After discussing with @LWallendal on the call, we decided to go for the overall roadmap (maybe a downloadable format e.g. PDF for now not to be too dependant on graphics). 
Would love help looking at [this document](https://docs.google.com/document/d/11gXUBvJjt6U2VgYDQvormAHBaivTlxzweSN-bzxno9w/edit) @pdyraga and @Shadowfiend  when you are back please

**Comment by elizapetrovska** [comment]
@Shadowfiend , gentle ping here, would love your eyes/thoughts/comments in the doc please

**Comment by Shadowfiend** [comment]
Going to see if I can make some updates here today based on our discussions last week!

**Comment by mhluongo** [comment]
We're so close to launch, we can kick this to when we open source
