### ISSUE TITLE
Update people on the website

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#134]
Add Dmitry, Nicholas, Olivia, Jarrell, Liam
Remove Philip, Raghav, Marcin, Aaron (see comment below for more details)

**Comment by elizapetrovska** [comment]
- Jarrell James: Ecosystem Growth & Innovation Lead

https://keybase.io/JarrellJames
https://www.linkedin.com/in/jarrell-james/
https://twitter.com/jarrelljames_


- Olivia Lovenmark: Writer & Communication Strategist

https://www.linkedin.com/in/olovenmark/
https://twitter.com/olivialovenmark
https://keybase.io/olivialovenmark


- Dmitry Paremski: Developer

https://keybase.io/dparemski
https://twitter.com/dmitry_paremski
https://github.com/dimpar
https://www.linkedin.com/in/paremski/


- Nicholas Evans: Developer

https://keybase.io/evansnicholaskb
https://github.com/nicholasdotsol
https://twitter.com/nicholasevans14


- Liam Zebedee: Developer

https://keybase.io/liamzebedee
https://twitter.com/liamzebedee
https://www.linkedin.com/in/liamedwardsplayne/
https://github.com/liamzebedee

**Comment by elizapetrovska** [comment]
These people are not in our Thesis Drive portrait folder:
 
![Dmitry](https://user-images.githubusercontent.com/35865315/61652299-3e711a80-ac7d-11e9-827c-ede30b2cf3c3.jpg)

![Jarrell](https://user-images.githubusercontent.com/35865315/61652448-94de5900-ac7d-11e9-90f3-f8e4dd78d6ff.jpeg)

![liam](https://user-images.githubusercontent.com/35865315/61652459-9ad43a00-ac7d-11e9-8727-5621c23aa77c.jpg)

**Comment by Shadowfiend** [comment]
Also adding Sloan while I'm at it.
