### ISSUE TITLE
Update center border on "Media Kit" section of Press Page

### ISSUE THREAD

**Issue by taggartbg** [keep-network/website#150]
Center border on "Media Kit" section of Press Page should be 50% transparent

**Comment by liz-shinn** [comment]
Current implementation:
<img width="1188" alt="Keep_Network" src="https://user-images.githubusercontent.com/57226633/69092455-69486100-0a1a-11ea-9e74-d03c4d4ee704.png">

Requested update:
<img width="871" alt="Keep_Website" src="https://user-images.githubusercontent.com/57226633/69093155-e0322980-0a1b-11ea-8c6c-f7a6d11c8cbf.png">
