### ISSUE TITLE
Press Page Nav in header not tracking location

### ISSUE THREAD

**Issue by taggartbg** [keep-network/website#151]
Press Page Nav link should show "active" state when on /press

**Comment by liz-shinn** [comment]
Current implementation:
<img width="1201" alt="Keep_Network" src="https://user-images.githubusercontent.com/57226633/69092290-0d7dd800-0a1a-11ea-93dc-83a434be9b90.png">

Updated to be:
<img width="705" alt="Keep_Website" src="https://user-images.githubusercontent.com/57226633/69092351-2d150080-0a1a-11ea-9fd1-49bfaa9d6c16.png">
