### ISSUE TITLE
Auto-deploy master and staging

### ISSUE THREAD

**Issue by mhluongo** [keep-network/website#16]

**Comment by mhluongo** [comment]
@sthompson22 now that we have standardized environments, is this something we can easily snipe?

**Comment by liz-shinn** [comment]
@mhluongo updates on this one or can this one be closed out?

**Comment by sthompson22** [comment]
The website is sadly still deployed to a pre-Sloan GCP environment.  I think we can close this and roll it up with a larger migration effort to retire these older environments.
