### ISSUE TITLE
Playing for Keeps on Keep Website (Prototype)

### ISSUE THREAD

**Issue by mhluongo** [keep-network/website#188]

**Comment by liz-shinn** [comment]
Figma file here: https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=1529%3A0

**Comment by creckhow** [comment]
This PfKs info will be integrated into the staking section. (current plan)

**what's the best name for this nav item?** (to pull in users looking for "how do I get KEEP?" see #191 ) 
- KEEP Distribution
- Staking
- Join the Network
- Get KEEP*
- Stake KEEP
- Earn KEEP*
- Stakedrop 
- Public Distribution
- Join the Community
- Work the Network

@mhluongo would love your thoughts here. we think "Staking" might not capture everyone looking for info on how to get KEEP and join the community....could 2 nav items be the answer?

**Comment by liz-shinn** [comment]
A draft of the design for this is available in Figma, going to close this out and partition these out into individual sections for the development work.
