### ISSUE TITLE
Main page captures stakedrop users

### ISSUE THREAD

**Issue by creckhow-zz** [keep-network/website#191]
We want people who are googling "keep stakedrop" who land on keep.network to immediately be brought to info on how to join. 

(Related to improving the stakedrop's SEO.)

**Comment by creckhow** [comment]
I left a comment in Figma about this @liz-shinn, it was on changing the "join the crowdcast" banner to bring people to the stakedrop page (or gitbook or discord, etc.). Basically this issue can be closed when we think we've got a solid 'yes' to the question of "are we sure people visiting keep.network for 2 seconds know immediately how to get KEEP and participate in the distribution offering". 

This is one for Amanda feedback too (she hasn't accepted the link cc @Shadowfiend can you drop it in a DM to her?) .

**Comment by creckhow** [comment]
This PfKs info will be integrated into the staking section. (current plan)

what's the best name for this nav item? (to pull in users looking for "how do I get KEEP?" see #191 )

KEEP Distribution
Staking
Join the Network
Get KEEP*
Stake KEEP
Earn KEEP*
Stakedrop
Public Distribution
Join the Community
Work the Network
@mhluongo would love your thoughts here. we think "Staking" might not capture everyone looking for info on how to get KEEP and join the community....could 2 nav items be the answer?
