### ISSUE TITLE
Consider which stakedrop page content is share-worthy & how

### ISSUE THREAD

**Issue by creckhow-zz** [keep-network/website#194]
Content that could be sharable = announcements, links to blog posts, sign-ups, discord.

This one needs to be broken down more to be a real user story

**Comment by creckhow** [comment]
tagging @liz-shinn and @Gluzman please assign yourself (and maybe @ironng later)...I'd guess this one needs a top level UX/design decision around how this is done consistently on the keep site... then you can break this down into more cards

**Comment by liz-shinn** [comment]
Deprecated with launch of the new Keep website design, closing this issue.
