### ISSUE TITLE
Design an IA for the stakedrop page 

### ISSUE THREAD

**Issue by creckhow-zz** [keep-network/website#197]
In particular -- staking documentation (aka stakedrop resource center aka gitbook) must be a dedicated section of the website with its own IA. 

Make sure to consider in IA: 
- announcements 
- new blogs about stakedrop 
- new guides or resources 

A quick reference guide for what the stakedrop is, a program timeline, etc.. Here are some of the things the header could do:

- give stakedrop definition (& link)
- give PfKs definition (& link)
- give stakedrop & PfKs dates (maybe a timeline graphic?)
- give staking ETH overview (diagram?)
- give brief definition of technical requirements for staking (like in #195 the 'basic info' mentioned?)

**Comment by creckhow** [comment]
@liz-shinn @Gluzman this one is the high level UX/IA card relating to several stakedrop page components #198 #196 #199 #193 #194 feel free to assign yourself (or close out if you think this is covered in #196 ) 

Also tagging @Shadowfiend @mhluongo @krisjpi for review of stakedrop page IA/frames.

**Comment by creckhow** [comment]
see #188 for brainstorm on nav heading....
