### ISSUE TITLE
Featured application module

### ISSUE THREAD

**Issue by mhluongo** [keep-network/website#211]
We've had a flood of people who learn about Keep but don't know anything about tBTC. Hoping to get a featured application module out early next week

@Gluzman pulled this out, I believe from @liz-shinn 's work in Figma.

<img width="973" alt="Screen Shot 2020-07-19 at 11 23 12" src="https://user-images.githubusercontent.com/427505/87882823-dc064380-c9d0-11ea-9a00-71601859d559.png">

He also said...

> I think also to simplify, ignore the parapet bottom edge

**Comment by liz-shinn** [comment]
Updated:

<img width="855" alt="featured" src="https://user-images.githubusercontent.com/57226633/87973863-70ec6800-cac9-11ea-8bea-0c21bc1e5211.png">

Button to website: https://tbtc.network/

Button to tbtc related blog post: https://blog.keep.network/introducing-tbtc-the-safest-way-to-earn-with-your-bitcoin-fec077f171f4

**Comment by liz-shinn** [comment]
@Shadowfiend – pulling this in here [from Flowdock](https://www.flowdock.com/app/cardforcoin/keep/threads/lgQQrFLtATYgdiGmTGZaIOcqqRU), there are a few notes on the buttons. Hover and active states for the primary and secondary buttons aren't aligning with buttons on the rest of the site. Here's how they should be:

<img width="883" alt="Screen Shot 2020-07-20 at 10 52 45 PM" src="https://user-images.githubusercontent.com/57226633/87985348-bb76e000-cadb-11ea-8731-8345ba7846af.png">


Currently there's underlined text on hover & active. Also, the secondary button should return to its default state after click; right now its staying in active and also growing in size:
<img width="659" alt="Screen Shot 2020-07-20 at 10 48 49 PM" src="https://user-images.githubusercontent.com/57226633/87985437-e5c89d80-cadb-11ea-9536-0eb3d725bfb2.png">
