### ISSUE TITLE
Keep Token Dashboard Product showcase module

### ISSUE THREAD

**Issue by creckhow-zz** [keep-network/website#220]
Section of the Keep website that leads to Keep token dashboard

**Comment by liz-shinn** [comment]
Working file for this: https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=337%3A0

**Comment by liz-shinn** [comment]
Current versions of this section cc/ @Shadowfiend @creckhow @Gluzman @mhluongo 

**Desktop**
<img width="755" alt="desktop-module-keep" src="https://user-images.githubusercontent.com/57226633/88061628-0a6a5700-cb68-11ea-8f3b-b99515ab46fb.png">

**Mobile**
<img width="195" alt="mobile-module-keep" src="https://user-images.githubusercontent.com/57226633/88061677-1d7d2700-cb68-11ea-9e3b-195a7a4c75b0.png">

**Comment by Gluzman** [comment]
these are WIP, product mockups are not final.

are we going to add this in this sprint?

**Comment by liz-shinn** [comment]
Based on standup, it sounded like no, but I think that this module should also go in if possible! Since it features the product.

**Comment by liz-shinn** [comment]
updated this:

![banner](https://user-images.githubusercontent.com/57226633/98049354-82018080-1dfd-11eb-95a5-52d060f52333.png)

In Figma here: https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=1616%3A0
