### ISSUE TITLE
Website prioritization / roadmap

### ISSUE THREAD

**Issue by creckhow** [keep-network/website#223]
Keep website roadmap & prioritization, post-brand session. 

Ideally completed by EOW 7/20

- [x] Meeting on Thurs 07/29

**Comment by liz-shinn** [comment]
Going to drop something on everyone's calendars for this! The Figma planning file for [the website content is here](https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=1737%3A7). Includes the messaging / brand positioning from the Google doc as well as a site map.
