### ISSUE TITLE
Messaging / brand positioning

### ISSUE THREAD

**Issue by creckhow** [keep-network/website#224]
Prior to Keep website planning & prioritization, hold a Keep brand & messaging session led by Amanda.

**Comment by liz-shinn** [comment]
This has been started in this process doc here: https://coda.io/d/Keep-Narrative_diwkeM16qMQ/Brand_suVdo#_luutI

As well as in this doc from a few months ago from Amanda here: https://blog.keep.network/introducing-tbtc-the-safest-way-to-earn-with-your-bitcoin-fec077f171f4

**Comment by liz-shinn** [comment]
Messaging / Brand strategy session last Friday with Matt, Michael, Liz, Carolyn, and Amanda.
This doc: https://docs.google.com/document/d/1x1ftIow98VXtdyu-8JR6vow1rCE8pCSxXTqhrI8MBH8/edit
