### ISSUE TITLE
What are we doing with gitbook?

### ISSUE THREAD

**Issue by creckhow-zz** [keep-network/website#225]
Q: Can we pull it natively into the site, can we get a single canonical doc site?

A: @liz did some research on this, we can give it a native sounding domain and link to it canonically in the new Keep website design. We cannot embed it.

**Comment by liz-shinn** [comment]
This issue references an existing issue: https://github.com/keep-network/website/issues/196

I don't think it's quite as simple as "can we embed the Gitbook or not." This relates to a much larger issue of how we handle documentation. It's [logged in the OKRs in (OKR 4, KR 2) as a stretch goal as well for this quarter](https://coda.io/d/OKRs_dD2I3UX5CIT/Q3-2020-OKRs-Keep-tBTC_subs3#Position-the-Keep-community-to-grow-into-an-ecosystem_tu7EP/r2).

For now, we can link out to the Gitbook from the website.
