### ISSUE TITLE
Revamp of the landing page header

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/website#227]
Changes the header of the Keep website to have a full screen image (@Gluzman and @liz-shinn are still deliberating w/ final image selection; there's a placeholder image for now).

Additional updates: 
- the header text and the subhead text are centered
- there are two centered chevron arrows, an affordance that you should scroll to continue through the rest of the website

Evaluating images here:
https://www.istockphoto.com/collaboration/boards/4JviEKJ1G06DCzdxLkGthQ
https://unsplash.com/collections/3121358/keep

**Comment by Shadowfiend** [comment]
Let me know where we landed here; I can look at picking it up next week.

**Comment by liz-shinn** [comment]
Screenshot of the latest draft of this is in [the Marketing flow here](https://www.flowdock.com/app/cardforcoin/tbtc-marketing/threads/JsR1R40OyIyPhetao6W6Yq6NURH). Pending team feedback!

**Comment by liz-shinn** [comment]
Added as an item to review during tomorrow's marketing call.

**Comment by liz-shinn** [comment]
Marketing call approval on this landing page update – all the copy, the two CTAs, and the background image are good to go. [All in Figma here](https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=1616%3A0). @Shadowfiend @mhluongo @creckhow 

<img width="714" alt="Screen Shot 2020-07-28 at 9 05 15 PM" src="https://user-images.githubusercontent.com/57226633/88709871-0ca75500-d116-11ea-9d39-7c95b03a3464.png">

**Comment by ironng** [comment]
@liz-shinn Did the jump to next section arrow at the bottom of the hero get dropped? I don't see it in figma or in the screenshot above - just want to verify.

**Comment by liz-shinn** [comment]
@ironng yup the jump to next section arrow did get dropped
