### ISSUE TITLE
Remove whitepaper link from Keep Applications section

### ISSUE THREAD

**Issue by liz-shinn** [keep-network/website#235]
Whitepaper download link is still present in the Keep Applications section:

<img width="543" alt="Screen Shot 2020-07-28 at 3 43 18 PM" src="https://user-images.githubusercontent.com/57226633/88673644-27afa000-d0e9-11ea-8c56-e6b203a25fbe.png">

**Comment by Shadowfiend** [comment]
Closing this in favor of #252, which will take care of it.
