### ISSUE TITLE
On the site the link to whitepaper is not active.

### ISSUE THREAD

**Issue by spopovss** [keep-network/website#250]
Our team found that the whitepaper link is not active.
Fix it.

**Comment by Shadowfiend** [comment]
The link is slated to be removed, as the whitepaper is outdated (#235). You can read or compile it yourself if you're interested at https://github.com/keep-network/whitepaper .

> Fix it.

Lastly, this is not an acceptable form of engaging with this team. We are not here to take your orders, we are here to hear your input :wink:

**Comment by spopovss** [comment]
> The link is slated to be removed, as the whitepaper is outdated (#235). You can read or compile it yourself if you're interested at https://github.com/keep-network/whitepaper .
> 
> > Fix it.
> 
> Lastly, this is not an acceptable form of engaging with this team. We are not here to take your orders, we are here to hear your input 😉

Sorry if my message seemed incorrect, we just found an error on the site and reported here.

**Comment by Shadowfiend** [comment]
Sorry, I should have explicitly flagged that it might be a language thing---we do appreciate you flagging the issue :heart:
