### ISSUE TITLE
Broken links to whitepaper in token dashboard dApp

### ISSUE THREAD

**Issue by eaorbita** [keep-network/website#255]
Broken links to Keep WhitePaper (https://backend.keep.network/whitepaper) on:
 - https://keep.network/ - "Keep Applications" section, "Learn More in the Whitepaper" link
 - https://dashboard.test.keep.network/ - footer section, "whitepaper" link

This is confusing when studying a project. I am a new member of the community and wanted to read about the project but could not find the white paper.

**Comment by liz-shinn** [comment]
Thanks for posting this issue! This issue is already logged here https://github.com/keep-network/website/issues/235

**Comment by eaorbita** [comment]
@liz-shinn , don't forget about https://dashboard.test.keep.network/ - footer section, "whitepaper" link, please

**Comment by liz-shinn** [comment]
Ah yes! I missed that it was also in the token dashboard.

@r-czajkowski could we remove the white paper link from the dApp?

cc/ @Shadowfiend

**Comment by liz-shinn** [comment]
I'm going to create a card for this in the token dashboard repo instead of the Keep website, since the white paper link has been addressed on the Keep website.
