### ISSUE TITLE
Governance forum section

### ISSUE THREAD

**Issue by Battenfield** [keep-network/website#413]
Add a section to the new Keep website for Governance forum
- CTA to the forum
- show the latest proposals

Design file: https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Website?node-id=3288%3A11290

**Comment by liz-shinn** [comment]
Created a separate card for the "How to Stake" addition to the Keep site. 

Here's the Governance section design:
cc/ @dougvk @Battenfield 

<img width="616" alt="Screen Shot 2021-05-25 at 4 52 56 PM" src="https://user-images.githubusercontent.com/57226633/119567158-f855d800-bd79-11eb-90a7-b54925eb87d6.png">

**Comment by liz-shinn** [comment]
Adjust height of cards to be uniform

**Comment by liz-shinn** [comment]
Updated card height:
<img width="578" alt="Screen Shot 2021-06-07 at 3 27 32 PM" src="https://user-images.githubusercontent.com/57226633/121076881-eaa24880-c7a4-11eb-95c9-7b41eaffc3cf.png">

This design is ready to go cc/ @Battenfield
