### ISSUE TITLE
Connect new Keep website staking information

### ISSUE THREAD

**Issue by Battenfield** [keep-network/website#414]
![keep_staking_apy](https://user-images.githubusercontent.com/7051522/117627743-530df380-b12d-11eb-987f-f8f376faffeb.png)

1. Hook up APY to live contracts for liquidity. Display estimates for KEEP staking/delegation.

2. Take the highest number APY and show it in the top header (replacing 200% APY):
>Stake on Ethereum’s first private computer and earn up to 200% APY.

3. Include an estimate of APY for staking KEEP?

**Comment by r-czajkowski** [comment]
Implemented in #431.
