### ISSUE TITLE
Add blog content section 

### ISSUE THREAD

**Issue by ironng** [keep-network/website#47]
<img width="1440" alt="screen shot 2017-12-27 at 11 50 01 am" src="https://user-images.githubusercontent.com/1986137/36807893-edc3e800-1c78-11e8-9ae3-d5e9694eb290.png">

**Comment by ironng** [comment]
@LWallendal I have the dev work for this completed on a branch [here](https://github.com/keep-network/website/tree/blog-content-section). We just need another quote/blurb (if you have one!) to separate this section from the others.

**Comment by LWallendal** [comment]
"One of the use cases we have on the roadmap for Aragon is having shared encrypted data vaults for DAOs — and I’d totally see Keep being a key part of it." - Luis Cuende, Aragon

**Comment by ironng** [comment]
@LWallendal Thanks for that! Do we have a picture for Luis? cc @gibson10ma 

Also, considering #69, what is the order you guys want for these sections?
