### ISSUE TITLE
Add new team members and partners!

### ISSUE THREAD

**Issue by ironng** [keep-network/website#48]
**Lex Sheehan - Developer**
https://github.com/l3x
https://www.linkedin.com/in/lexsheehan/
https://twitter.com/lex_sheehan?lang=en
https://keybase.io/l3x

**Raghav Gulati - Developer**
https://www.linkedin.com/in/rargulati/
https://twitter.com/rargulati
https://github.com/rargulati
https://keybase.io/raj

**Philip Schlump -Developer**
https://keybase.io/pschlump
https://twitter.com/pschlump
https://www.linkedin.com/in/philip-schlump-73100429/ Feb 27, 2018 5:50
https://github.com/pschlump

**Eliza Petrovska - Community Manager**
https://keybase.io/elizapetrovska
https://twitter.com/elizapetrovska
https://github.com/elizapetrovska

**Hope Cowan - Support**
https://keybase.io/hecowan
https://www.linkedin.com/in/hopecowan/

[Bios.zip](https://github.com/keep-network/website/files/1768535/Bios.zip)
[Logo.zip](https://github.com/keep-network/website/files/1768536/Logo.zip)
![screen shot 2018-02-28 at 8 38 58 am](https://user-images.githubusercontent.com/1986137/36808533-357ee482-1c7a-11e8-8e35-a42b4d036b58.png)
[Archive.zip](https://github.com/keep-network/website/files/1768540/Archive.zip)

**Comment by mhluongo** [comment]
Closed by #49
