### ISSUE TITLE
Media pack and simple brand guidelines

### ISSUE THREAD

**Issue by mhluongo** [keep-network/website#57]
Folks on Slack are asking for vector logos, etc

![image](https://user-images.githubusercontent.com/427505/39949659-25a3a166-554a-11e8-80c7-21acb6386df9.png)

It'd be good for press and partnerships to have eg https://keep.network/media

**Comment by Gluzman** [comment]
beginning a list of needs—plz add anything i may have missed:

> logo (all colors)
> single K icon (all colors)
> K icon in circle (token look) 
> Keep Corps — should this have a wordmark?

**Comment by mhluongo** [comment]
Let's nix Keep Corps for now. Better to get this out in a limited way and iterate @Gluzman

**Comment by liz-shinn** [comment]
Duplicate issue; updates to this referenced in: https://github.com/keep-network/website/issues/171
