### ISSUE TITLE
Replace the primer with the file attached

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#59]
[KeepBusinessPrimer.pdf](https://github.com/keep-network/website/files/2107112/KeepBusinessPrimer.pdf)
@ @Shadowfiend

**Comment by Shadowfiend** [comment]
Looks like there's still a table of contents entry for the dev roadmap, and the page numbers are off by one after that.

**Comment by elizapetrovska** [comment]
[keepBusinessPrimer june 18.pdf](https://github.com/keep-network/website/files/2112213/keepBusinessPrimer.june.18.pdf)

We just thought we will do it in 2 stages as I did not have keynote access due to silly reasons.
Anyway! THIS IS THE ONE!

**Comment by Shadowfiend** [comment]
Nice! Erm… @ironng when you do the Piotr/Kuba update, you mind updating this file as well?

**Comment by ironng** [comment]
Will do! I can also get in @elizapetrovska's other small updates :)

**Comment by elizapetrovska** [comment]
Please replace with this one

[keepBusinessPrimer 6.07.2018.pdf](https://github.com/keep-network/website/files/2172247/keepBusinessPrimer.6.07.2018.pdf)
