### ISSUE TITLE
Add two new employees (pics and social links attached)

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#61]
Piotr Dyraga, Developer

![piotr](https://user-images.githubusercontent.com/35865315/41488892-efb5f4a4-70bb-11e8-8786-5078446dc234.JPG)

https://www.linkedin.com/in/piotrdyraga/
https://twitter.com/piotrdyraga?lang=en
https://github.com/pdyraga

Jakub Nowakowski, Developer
![jakub](https://user-images.githubusercontent.com/35865315/41488895-f2249e2a-70bb-11e8-8dd9-9653f789ca58.JPG)

https://www.linkedin.com/in/jnowakowski8/
https://twitter.com/jnowakow8
https://github.com/nkuba

@Shadowfiend

**Comment by Shadowfiend** [comment]
@ironng any chance you can add these? I'm a little swamped this week.

**Comment by ironng** [comment]
@Shadowfiend Sure thing, I'll get them in soon

**Comment by Shadowfiend** [comment]
Thank youuu :heart::heart::heart:

**Comment by elizapetrovska** [comment]
Oh Antonio but it is not done?

**Comment by Shadowfiend** [comment]
<img width="1016" alt="screen shot 2018-06-22 at 09 00 51" src="https://user-images.githubusercontent.com/8245/41780593-c7d40180-75fa-11e8-954a-2a69ad35da4b.png">

Looks done to me, no? ^

**Comment by elizapetrovska** [comment]
Yes!!! Now yes! Sorry! I checked last night and it was not:)

**Comment by Shadowfiend** [comment]
Ok cool :)
