### ISSUE TITLE
Please replace the primer with the one attached here

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#71]
[keepBusinessPrimer 11.07.2018.pdf](https://github.com/keep-network/website/files/2186349/keepBusinessPrimer.11.07.2018.pdf)

**Comment by elizapetrovska** [comment]
@Shadowfiend @ironng

**Comment by ironng** [comment]
@elizapetrovska @Shadowfiend Should we update the primer with the org change first?

**Comment by elizapetrovska** [comment]
Please give me just 20 minutes :) I am updating it right now

**Comment by elizapetrovska** [comment]
Done!!!

**Comment by ironng** [comment]
Thank you! Will update on the site now.
