### ISSUE TITLE
Please update "Our latest content", replace all 3

### ISSUE THREAD

**Issue by elizapetrovska** [keep-network/website#73]
3 last articles are:
https://blog.keep.network/keep-roundup-september-2018-a73d3887678c
https://blog.keep.network/random-beacon-alpha-api-and-demo-app-9b8f9c6347b6
https://blog.keep.network/building-a-beacon-the-road-to-mainnet-6e1904f0c986

**Comment by elizapetrovska** [comment]
@ironng ?

**Comment by elizapetrovska** [comment]
@Shadowfiend ?

**Comment by ironng** [comment]
@elizapetrovska Sorry I've just been really busy on the Fold side. I can take care of this this week. Does that work?

**Comment by Shadowfiend** [comment]
@ironng let's revisit after SFBW unless you find yourself with unexpected spare cycles, alongside keep-network/website-backend#7 and keep-network/website-backend#8 (assuming those are also in your wheelhouse).

**Comment by ironng** [comment]
@Shadowfiend Ok, sounds good thanks!
