### ISSUE TITLE
Lendroid Link attached to logo is dead

### ISSUE THREAD

**Issue by afmsavage** [keep-network/website#95]
The Lendroid URL attached to their logo on the website is dead.  Lendroid does not have the correct DNS mapping setup for https://lendroid.com to work, so you need to enter the www as well.  The correct fix is for them to fix their DNS and to leave the link as is.

**Comment by Shadowfiend** [comment]
Not necessarily! Different folks think differently about using their non-www domains directly or not ;) We'll see about shooting them a note, but in the meantime it's clear they consider the `www` version the canonical version.

Thanks for the note!

**Comment by mhluongo** [comment]
Closed by #96, thanks @afmsavage!
